version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  php:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # Add any additional configuration needed

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_assignment
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  mysql_data:
